name: T-Edit
version: '1.0' # Increment version
main: com.takeda.TEditPlugin
api-version: '1.21'
authors: [ Takeda ]
description: Advanced item editing GUI.

commands:
  edit:
    description: Opens the T-Edit GUI for the held item.
    usage: /<command>
    permission: tedit.use
    aliases: [ itemedit, iedit, te ]
  # New admin command branch
  tedit:
    description: T-Edit administrative commands.
    usage: /<command> <subcommand>
    permission: tedit.admin # Base permission for admin commands (optional)
    aliases: [ teadmin ]
    # Subcommands handled internally (e.g., reload)

permissions:
  tedit.*:
    description: Grants all T-Edit permissions.
    default: op
    children:
      tedit.admin: true # Grant admin base perm
      tedit.use: true
      # Add children from below for completeness if desired

  # Admin Permissions
  tedit.admin:
    description: Allows access to administrative /tedit commands.
    default: op
    children:
      tedit.reload: true

  tedit.reload:
    description: Allows reloading T-Edit configuration via /tedit reload.
    default: op

  # User Permissions
  tedit.use:
    description: Allows using the /edit command to open the GUI.
    default: op
  tedit.rename:
    description: Allows using the rename feature.
    default: op
  tedit.lore.edit: # Covers adding lore for now
    description: Allows adding lore lines.
    default: op
  tedit.lore.clear:
    description: Allows clearing all lore lines.
    default: op
  tedit.enchant.base:
    description: Allows basic enchanting actions (viewing, applying non-special enchants).
    default: op
  tedit.enchant.bypasslevel:
    description: Allows enchanting above vanilla level caps (requires config enabled).
    default: op
  tedit.enchant.bypassconflict:
    description: Allows applying conflicting enchantments (requires config enabled).
    default: op
  tedit.enchant.treasure:
    description: Allows applying treasure enchantments (requires config enabled).
    default: op
  tedit.enchant.curses:
    description: Allows applying curse enchantments (requires config enabled).
    default: op
  tedit.repair:
    description: Allows using the repair feature.
    default: op
  tedit.duplicate:
    description: Allows using the duplicate item feature.
    default: op